# Generated by Django 5.1.3 on 2024-11-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthKey',
        ),
    ]
